# Site settings
title: Object Detection Training
description: >-
  Create custom object detection models for TensorFlow.js
baseurl: "/training" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: bourdakos1
github_username:  bourdakos1

# Build settings
markdown: kramdown
theme: minima

# Authors
authors:
  - name: Nick Bourdakos
    twitter: bourdakos1
    github: bourdakos1

collections:
  object_detection:
    output: true
    permalink: /object-detection/:path:output_ext
  wml_object_detection:
    output: true
    permalink: /object-detection/wml/:path:output_ext
  classification:
    output: true
    permalink: /classification/:path:output_ext
  wml_classification:
    output: true
    permalink: /classification/wml/:path:output_ext

defaults:
  - scope:
      path: ""
      type: "object_detection"
    values:
      layout: index
  - scope:
      path: ""
      type: "wml_object_detection"
    values:
      layout: index
  - scope:
      path: ""
      type: "classification"
    values:
      layout: index
  - scope:
      path: ""
      type: "wml_classification"
    values:
      layout: index
